version: '3.8'

services:
  db:
    image: mysql:5.7.32
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33067:3306"
    volumes:
      - .dbdata:/var/lib/mysql

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: python consumer.py
    environment:
      FLASK_APP: main
    restart: on-failure
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    environment:
      FLASK_APP: main
    ports:
      - "8001:5000"
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      - db
      - queue
