version: '3.8'

services:
  db:
    image: mysql:5.7.32
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33067:3306"
    volumes:
      - .dbdata:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: main
      DATABASE_URL: 'mysql://root:root@0.0.0.0:33067/main?charset=utf8'
    ports:
      - "8001:5000"
    volumes:
      - .:/app
    depends_on:
      - db
