version: '3.8'

services:
  db:
    image: mysql:5.7.32
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33066:3306"
    volumes:
      - .dbdata:/var/lib/mysql

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: python consumer.py
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
